### ISSUE TITLE
Gboard starts misbehaving once message in composer is marked as a reply

### ISSUE THREAD

**Issue by rom4nik** [element-hq/element-x-android#2092]
### Steps to reproduce

1. Type text into composer using Gboard
2. Swipe on a message to make current message a reply
3. Continue typing or deleting text in composer

#### What did you expect?
Autocorrect works fine, suggestions bar doesn't flicker, typing or deleting characters doesn't cause current word to be reinserted a few more times into composer (e.g. typing `e` after `thirt` can cause `thirtthirtthirtthirte` to be inserted instead of `thirte`; similarly deleting `e` from `thirte` can put `thirtethirthethirt` in composer).

#### What happened instead?

https://github.com/element-hq/element-x-android/assets/46846000/d00ae6c7-1e5e-4cbd-9cb0-7fa307bdc46e

Notice that flickering starts only after swiping to reply, and that some characters are deleted with higher delay than others.

I think this might have happened to me a few times while editing messages too.

### Your phone model

Google Pixel 3

### Operating system version

Android 13

### Application version and app store

deff2d8, GHA debug build

### Homeserver

Synapse 1.98.0

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Thanks for reporting. I understand the description you provided, but I do not clearly see the bug in the video you posted. Will try to repro.

**Comment by rom4nik** [comment]
Right, here's another video:

https://github.com/element-hq/element-x-android/assets/46846000/6cf93e94-3a83-47b4-9280-64bfe97d2fea

1. 0-13s - typing words before swiping to reply, suggestions bar doesn't flicker, autocorrect marks suggestions in bold (to be applied automatically after pressing space)
2. 14s - swiped to reply, first flicker of suggestions bar
3. 14-19s - flickers after typing (almost?) every letter
4. 19s - first typo in `trhee`, notice that Gboard doesn't intend to automatically correct it (`three` has regular font)
5. 29s - another typo, same behavior
6. 33-46s - deleting text, suggestions bar flickers when I'm removing letters one by one, and doesn't flicker only when I'm deleting letters of the first `one`
7. 51-54s - accidental 2 letter typo in `fuir`, not captured in video but Gboard apparently wouldn't autocorrect that anyway
8. 59s-1m5s - intentional typo in `sveen`, Gboard would've autocorrected that

I'm not sure if that's what's happening here, but Gboard kind of behaves as if I switched between apps (see video below) after every inserted letter here - like it doesn't "remember" that all those letters were inserted by Gboard itself just a moment ago.

https://github.com/element-hq/element-x-android/assets/46846000/3473f8c7-5131-4ce0-ad17-d069aef9c5f2

**Comment by jmartinesp** [comment]
Technically there are 2 text fields here: one in usage and one hidden, and they're both needed to measure the full screen and collapsed states. So my bet is, as this is an `EditText` under the hood, Compose isn't handling this properly.

Sadly, replacing the `EditText` with a pure Compose `TextField` is not going to happen any time soon since it would involve a lot of work in the RTE library, and we can't just disable the full screen feature either so we just need to use a single `EditText`.

We'll either have to find a way to kill the existing composing session in the previous `EditText` when the switch to the next one happens or live with the issue for the time being.

**Comment by rom4nik** [comment]
I see. In the meantime I've managed to observe and record the other bug here, where words are repeatedly inserted while typing/deleting characters.

https://github.com/element-hq/element-x-android/assets/46846000/41bf3102-ab08-4ebc-98e4-8481117d61e0

It seems that to quite repeatedly reproduce this I have to type some text into "plain" composer first, then swipe to reply, then enable RTE toolbar and type more text, optionally using `code` tool.

**Comment by Vikingtons** [comment]
For what it's worth, similar behaviour can be observed with OpenBoard, specifically when editing sent messages. Not sure of this warrants a distinct ticket.

**Comment by Ezwen** [comment]
I think this bug is not related to Gboard, as I can reproduce it both with the AOSP keyboard and the OpenBoard keyboard.

**Comment by Vikingtons** [comment]
This issue is now present outside of replies as of 0.4.6

https://github.com/element-hq/element-x-android/assets/9853124/8eddba54-1f9a-4e1b-af67-e609c9d5e139

**Comment by jokeyrhyme** [comment]
I trigger this bug so frequently that I have disabled the Rich text editor in Settings -> Advanced

I'm not sure what's special about my usage, but I do select and replace previously-typed text, and move the cursor around to insert/correct text, and I do use a mix of tap-to-type, swipe-to-type and auto-completion features in Gboard

**Comment by Vikingtons** [comment]
> I trigger this bug so frequently that I have disabled the Rich text editor in Settings -> Advanced
> 
> I'm not sure what's special about my usage, but I do select and replace previously-typed text, and move the cursor around to insert/correct text, and I do use a mix of tap-to-type, swipe-to-type and auto-completion features in Gboard
> 
> I do also use back-ticks to try to create `code` formatting quite often, too

I've seen this workaround mentioned in the EXA matrix room but it doesn't seem to do the trick for me. Do you mind me asking which keyboard you're using?

**Comment by maltee1** [comment]
For me, as of 0.4.7, this bug (or a similar one) affects GBoard, OpenBoard, SwiftKey and Anysoft. I haven't found any keyboards with autocorrect that aren't affected. It's independent of reply, edit or just normal message. Disabling the rich text editor makes no difference. What I noticed in particular is that I can't delete individual letters anymore using backspace (such as the first letter of a word I'm teying to delete)

**Comment by jokeyrhyme** [comment]
> Disabling the rich text editor makes no difference.

Are you sure it was disabled

I reproduced the issue today in a reply, and when I checked, the rick text editor was re-enabled mysteriously

Perhaps the app automatically resets it to default on every time it launches or something?

**Comment by Ezwen** [comment]
> For me, as of 0.4.7, this bug (or a similar one) affects GBoard, OpenBoard, SwiftKey and Anysoft. I haven't found any keyboards with autocorrect that aren't affected. It's independent of reply, edit or just normal message. Disabling the rich text editor makes no difference. What I noticed in particular is that I can't delete individual letters anymore using backspace (such as the first letter of a word I'm teying to delete)

Same here, app now unusable on my end as well

**Comment by maltee1** [comment]
> Are you sure it was disabled?

Yes. I tried both settings of the slider and one of resulted in "text formatting" being unavailable. Both showed the same behaviour with respect to garbling text.

**Comment by parisni** [comment]
> Same here, app now unusable on my end as well

Same problem (I mean unusable). synapse 1.98 / elementx 0.4.7 / openboard + iodeOS 4.10

The only workaround i have is writing message without spaces.

imeanihavetowritelikethisinelementxotherwiseitgets crarararsersssyysysysysysyss

**Comment by parisni** [comment]
For me workaround is to disable the auto correction in openboard. It means disabling for any application so it's quite annoying. But this way elementx is noy affected by the issue

**Comment by maltee1** [comment]
Got it fixed by updating GBoard, someone else confirmed heliboard 1.2 is also working

**Comment by Ezwen** [comment]
> For me workaround is to disable the auto correction in openboard. It means disabling for any application so it's quite annoying. But this way elementx is noy affected by the issue

This did not work for me, or maybe I did not disable the right option?

**Comment by Ezwen** [comment]
> Got it fixed by updating GBoard, someone else confirmed heliboard 1.2 is also working

in my case, problem still occuring when I tried with heliboard 1.2 today.

**Comment by witchent** [comment]
> > For me workaround is to disable the auto correction in openboard. It means disabling for any application so it's quite annoying. But this way elementx is noy affected by the issue
> 
> This did not work for me, or maybe I did not disable the right option?

You have to disable both "Auto-correction" and "Show correction suggestions" in the "Text correction" part of the HeliBoard settings. But this is a really bad solution so I hope at one point either element-x or heliboard finds a solution for this problem (which is the only combination where I have this problem)

**Comment by Ezwen** [comment]
> > > For me workaround is to disable the auto correction in openboard. It means disabling for any application so it's quite annoying. But this way elementx is noy affected by the issue
> > 
> > 
> > This did not work for me, or maybe I did not disable the right option?
> 
> You have to disable both "Auto-correction" and "Show correction suggestions" in the "Text correction" part of the HeliBoard settings. But this is a really bad solution so I hope at one point either element-x or heliboard finds a solution for this problem (which is the only combination where I have this problem)

Thanks, I can confirm that disabling both "_Auto-correction_" and "_Show correction suggestions_" make the problem disappear **both with Openboard and Heliboard**. In each case, I tried writing a new message, or replying to a message, or editing a message, and no problem appeared.

… but I agree with @witchent, writing without autocorrect in all apps is not a very comfortable solution :)

**Comment by jmartinesp** [comment]
Sorry for the trouble. This issue was fixed yesterday in the rich text editor library [here](https://github.com/matrix-org/matrix-rich-text-editor/pull/955), however we still need to release a version of the library and integrate it in the app, we're just waiting for some other changes to be merged.

**Comment by returntrip** [comment]
Confirming it works on 0.4.8. Thanks!
