### ISSUE TITLE
confirming recovery after update doesnt accept correct recovery key

### ISSUE THREAD

**Issue by kinghat** [element-hq/element-x-android#2098]
### Steps to reproduce

after the update to 0.4.0 it is telling me the backups are out of sync and i need to confirm my recovery key.

#### What did you expect?
backups not be out of sync? entered recovery key to be correct.
#### What happened instead?
the correct key isnt accepted.

### Your phone model

pixel 2 xl

### Operating system version

android 13

### Application version and app store

element x version 0.4.0

### Homeserver

Homeserver is https://matrix-client.matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by maresmar** [comment]
I also cannot use a key from my KeePass. Is a "recovery key" a correct term? I was unable to find it in the Element Web and it looks like the term was changed recently:

> recovery key is a deprecated name of security key

see https://github.com/element-hq/element-web/issues/15500#issuecomment-864579422

> there's lingering uses of "Recovery Key" still, as you have found in the validation message, so those should likely be replaced.

see https://github.com/element-hq/element-web/issues/15500#issuecomment-713673647

**Comment by returntrip** [comment]
In my case a very old recovery key is accepted and confirmed but the chat backup remains off sync

**Comment by kinghat** [comment]
im not having the issue anymore. it still shows that i need to confirm my recovery key but it goes away after a few seconds now. should i close this?

**Comment by returntrip** [comment]
Please keep it open I still get this problem

**Comment by spaetz** [comment]
Same here, recovery key is not accepted in element-x. I confirmed that the same key is correct in Android element.

**Comment by jmartinesp** [comment]
@returntrip, @spaetz , could you try using your recovery keys and them upload some logs by using the bug reporting feature  in settings? It might help confirm if it's the same one we're seeing on iOS and provide more info for debugging.

**Comment by returntrip** [comment]
Done!

**Comment by 0x1a8510f2** [comment]
Also seeing this issue. Using a self-hosted dendrite.

**Comment by spaetz** [comment]
Uhh, I was also using a self-hosted dendrite, so perhaps that is a common issue. I have since swit hed overnto synapse, but have not set up sliding sync yet, so I can't test right now.

**Comment by uumas** [comment]
I'm getting this same issue on a new login. Login -> verify with other session -> Element X asks to confirm recovery key. The correct one isn't accepted but it asking for that is a bug in itself. I uploaded logs after a fresh login with this issue number in comment.

**Comment by uumas** [comment]
I'm having this issue on synapse

**Comment by wavexx** [comment]
I'm having this on the official matrix.org server.
- New install
- Logged in
- Got prompted to enter the recovery key
- Key is actually _accepted_ once I press continue
- Message asking to confirm the recovery key still reappears after a while.
- 99% of old ee messages get decrypted successfully, so the backup seems to be restored, but some recent ones (usually a couple in a single chat) remain with "waiting for this message" forever

If I repeat the process, the messages which remain in "waiting for this message" state changes (and I get the previous ones back), so there seems to be some issue there..

**Comment by subscribernamegoeshere** [comment]
I am also having this issue, long term matrix.org account user. using element web/desktop on linux, in firefox linux and on a single android device using the classical element from google play-store and additionally some months ago I also additionally somewhat use and compare the element-x android. some when a while back, element-x-android (only) started showing this notification to "confirm your recovery key" only on element-x-android, nowhere else. I am always scared of such cryptography and maybe? data-loss  prone situations, I dont want to lose my chats, I only have a very few communications ongoing. all the other element applications web-page etc dont show any problems. only the element-x-android shows this complaint. what to do about it? i do have recovery keys or strings or whatever those technical terms were when I created the account and some when fetched downloaded or exported those security settings. I really dont want to mess up my account and my chats and all. any advice? will us users need to do anything about it or just wait for some fix in the element-x-android client? thank you.

**Comment by subscribernamegoeshere** [comment]
so I do have to enter something it will not go away with a fix? just wondering as this message didnt come up originally when I very first logged into the modern element-x-android in the first place. it was doing fine without this request for recovery key for a number of weeks. until that december update to 0.4.0 I guess.

**Comment by 0x1a8510f2** [comment]
I think they only added the feature to use key backup in that version. It is expected that you see that notification and have to enter your recovery key once. The bug is that the correct recovery key isn't accepted. So once that bug is fixed in the next release after this issue is closed, try entering the recovery key again.

**Comment by bmarty** [comment]
The refresh UI issue has been fixed in https://github.com/element-hq/element-x-android/pull/2421, there was an issue on the state observer.

Can you confirm it's fixed on the latest nightly and/or on EXA 0.4.5?

Thanks

**Comment by returntrip** [comment]
Issue persists for me on 0.4.5

**Comment by wavexx** [comment]
Issue persists for me as well with 0.4.5:

- "Enter your recovery key" shown at startup
- Using the button now goes directly to the recovery key prompt
- I enter the recovery key and confirm
- Goes back to the main screen showing "Recovery key confirmed"

Red dot still visible, "Enter your recovery key" popup still there. Going to the settings->chat backup still shows "your chat backup is currently out of sync".

No change in behavior whatsoever.

**Comment by bmarty** [comment]
Tested again today and cannot repro.
We have made the session verification mandatory during the sign in flow, so for people who still have the problem, please signout, clear application data storage and sign in again, using the latest EXA version (0.4.13).
Thanks.

**Comment by wavexx** [comment]
I submitted a couple of reports with logs directly from element X when using 0.4.13, I hope those got picked up.

I cleared storage/cache, then tried again on 0.4.13 from scratch:

- logged in
- verified using the recovery key
- "your device is verified"
- immediately afterwards, popup "enter your recovery key" (your chat backup is out of sync)
- i tap on it, enter the same recovery key again, hit confirm
- confirm button spins, then stays disabled, nothing happens

No change in behavior from my side, still 100% reproducible.

**Comment by wavexx** [comment]
To continue, if I go manually go through the chat backup -> enter recovery key, the behavior is slightly different but results in the same:

- start element x
- see "enter recovery key" popup
- go through settings -> chat backup -> enter recovery key
- enter recovery key, hit continue
- continue spins, dismisses the page and goes back to "chat backup" settings, with the red dot still indicating the backup is out of sync

On my side, I just wish I could at least permanently silence that popup/indicator.

**Comment by uumas** [comment]
and for me it still says incorrect recovery key. I sent logs of a fresh login on 0.4.14 after
- signing in
- verifying the session with another session
- seeing the red dot in settings -> going to chat backup -> entering the recovery key
- having it tell me the recovery key was incorrect

**Comment by ThisNekoGuy** [comment]
With version 0.7.0, I also have my correct recovery key rejected for some reason. I saved mine in a password manager when I got it, so I know the key is correct. :/

**Comment by ThisNekoGuy** [comment]
With version 0.7.0, I also have my correct recovery key rejected for some reason. I saved mine in a password manager when I got it, so I know the key is correct. :/

This happens even if I sign out, wipe the cache, then do it from the first-time login process... @bmarty

**Comment by manuroe** [comment]
We made a fix on the navigation in https://github.com/element-hq/element-x-android/pull/3961. It is in the app since 0.7.5. Please create a ticket and submit an rageshake if you meet the problem.

**Comment by returntrip** [comment]
This is still a problem for me even after EX 0.7.6. I have logged out and back in.

**Comment by mxrch** [comment]
Hey, I still have this issue on Element X 25.03.0.
If I enter the wrong recovery key, it says it's invalid, but if I enter the good one, it just does nothing and redirects me to the homepage, with the popup for recovery key still being shown.

**Comment by mxrch** [comment]
> Tested again today and cannot repro. We have made the session verification mandatory during the sign in flow, so for people who still have the problem, please signout, clear application data storage and sign in again, using the latest EXA version (0.4.13). Thanks.

@bmarty I just confirmed this solution does not resolve the bug. We should re-open this issue ?

**Comment by weeman1337** [comment]
This does still happen with Element X 25.06.2

**Comment by beerlion** [comment]
This does still happen with freshly installed EX 26.04.4.
EX doesn't accept recovery key "got" from mheko. If I run mheko with blank profile, mheko still successfully accept the key.
It seems that it would be better to first “generate” a new key via EX and only then go to other devices.
