### ISSUE TITLE
Ringing does not stop in the room even when caller hangs up

### ISSUE THREAD

**Issue by rajil** [element-hq/element-x-android#3014]
Bug filed [here](https://github.com/element-hq/element-call/issues/2421).

**Comment by bmarty** [comment]
I think this is fixed by https://github.com/element-hq/element-x-android/pull/3047

**Comment by rajil** [comment]
No, it is not fixed as tested against 0.4.16-nightly (develop 3d27f26d). The call is not torn down when caller A hangs up. The ring continues on devices B and C. The improvement is that if B and C join the call they see each other (i.e. video conference gets established).
