### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by Destinyg133** [element-hq/element-x-android#4194]
### Steps to reproduce

App crashes on s22ultra

![Image](https://github.com/user-attachments/assets/3dcb1a88-057c-4edd-9bc9-fbb2382254fa)

#### What happened instead?
Crash

### Your phone model

Samsung s22 ultra

### Operating system version

android 14

### Application version and app store

element 0.7.6

### Homeserver

synapse 1.122

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
We have fixed some ANR on the latest version 25.02.0.

Without a stacktrace or a way to reproduce, it will be hard to investigate this issue.

**Comment by Destinyg133** [comment]
@bmarty can confirm with new version it still happens. Issue seems to be only on samsung phones
