### ISSUE TITLE
Videos fail to send

### ISSUE THREAD

**Issue by Destinyg133** [element-hq/element-x-android#4243]
### Steps to reproduce

Some videos fail to send
I will include log, hopefully it can help 
They can be sent using element-android normally but with EXA it just fails or goes into neverending loop

[logs.2025-02-07-11.log](https://github.com/user-attachments/files/18705560/logs.2025-02-07-11.log)
[logcat.log](https://github.com/user-attachments/files/18705559/logcat.log)

#### What did you expect?
To send video files normally

#### What happened instead?
Neverendinf loop or failed to send message

### Your phone model

mi10t

### Application version and app store

synapse 1.123

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
I see:

```
matrix_sdk::http_client::native: Sending request num_attempt=1 | crates/matrix-sdk/src/http_client/native.rs:55 | spans: send_attachment > send_attachment > prepare_and_send_attachment > send{server_versions=[V1_0, V1_1, V1_2, V1_3, V1_4, V1_5, V1_6, V1_7, V1_8, V1_9, V1_10, V1_11] config=RequestConfig { timeout: 532s } request_id="REQ-51" method=POST uri="https://domain.tld/_matrix/media/v3/upload" request_size="63.4 MiB" status=502 response_size="0 B" status=502 response_size="0 B" status=502 response_size="0 B" status=502 response_size="0 B" status=502 response_size="0 B" status=502 response_size="0 B" status=502 response_size="0 B"}
```

So you're getting a 502 status code from the homeserver. This status code is usually returned for errors with federation, could you confirm whether the room you're uploading the videos too is in the same HS as you or on a different one? There might be some issue in the SDK preventing uploading media through federation from working properly.

Another option is the 502 could mean the file is too large, but AFAICT this is only used in the `/download` endpoint when HS can't serve a media that large, not for uploading media.

**Comment by jmartinesp** [comment]
After checking the related synapse code and confirming nothing should be returning a `502` status code I asked the synapse backend team about this issue and they said it would most likely be caused by your reverse proxy limiting the size of uploaded files and returning the `502` http status code. 

Could you double check if that's the case? Maybe it's working on EA because the video is compressed with higher compression and passes this check?

**Comment by Destinyg133** [comment]
> After checking the related synapse code and confirming nothing should be returning a `502` status code I asked the synapse backend team about this issue and they said it would most likely be caused the file being larger than your synapse's `max_upload_size` config field, which would cause it to drop the connection and your reverse proxy returns a `502` status code when that happens.
> 
> Could you double check if that's the case? Maybe it's working on EA because the video is compressed with higher compression and passes this check?

Already tried uploading other much bigger files, they seem to upload fine
Videos seem to be problem
Even some smaller ones

**Comment by jmartinesp** [comment]
Then I'm sorry to ask again, but could you give us some more info about the videos (format, codec, size maybe?) and upload additional logs when you receive an error uploading them? Sadly, we need some more info to debug this issue.

**Comment by Destinyg133** [comment]
> Then I'm sorry to ask again, but could you give us some more info about the videos (format, codec, size maybe?) and upload additional logs when you receive an error uploading them? Sadly, we need some more info to debug this issue.

[logcat (1).log](https://github.com/user-attachments/files/18736984/logcat.1.log)
https://github.com/user-attachments/assets/9d4e7ca4-6886-4b3d-b482-f02a3a948008

![Image](https://github.com/user-attachments/assets/9cc8af47-e591-4fa0-ad4d-b642f08eafd3)

**Comment by jmartinesp** [comment]
Thanks for the logs and video! I think I found the issue:

```
02-10 16:44:15.737 21648 22013 E TranscodeEngine: Unexpected error while transcoding.
02-10 16:44:15.737 21648 22013 E TranscodeEngine: java.lang.IllegalStateException: Timestamps must be monotonically increasing: 0, 0
```

Which *should* be fixed by https://github.com/element-hq/element-x-android/pull/4247 once merged (should, but I couldn't confirm it does because I can't reproduce the issue, not even with your video).

If you want to double check, you can download the APK [in the PR](https://github.com/element-hq/element-x-android/pull/4247#issuecomment-2643547587) to test the fix, just take into account this will be installed as a separate app and it's in debug mode, so performance is way worse than on an officially released one.

**Comment by Destinyg133** [comment]
> Thanks for the logs and video! I think I found the issue:
> 
> ```
> 02-10 16:44:15.737 21648 22013 E TranscodeEngine: Unexpected error while transcoding.
> 02-10 16:44:15.737 21648 22013 E TranscodeEngine: java.lang.IllegalStateException: Timestamps must be monotonically increasing: 0, 0
> ```
> 
> Which _should_ be fixed by [#4247](https://github.com/element-hq/element-x-android/pull/4247) once merged (should, but I couldn't confirm it does because I can't reproduce the issue, not even with your video).
> 
> If you want to double check, you can download the APK [in the PR](https://github.com/element-hq/element-x-android/pull/4247#issuecomment-2643547587) to test the fix, just take into account this will be installed as a separate app and it's in debug mode, so performance is way worse than on an officially released on

Same thing. Still not working

[logcat (1).log](https://github.com/user-attachments/files/18737380/logcat.1.log)

**Comment by jmartinesp** [comment]
I'm sorry to hear that, could you try again with [this one instead](https://github.com/element-hq/element-x-android/pull/4257#issuecomment-2648735567)?

Here we try to use a time interpolator that forces the timestamps to be linear, which should fix the issue, but I'm not sure if that could break the video somehow. I'm also trying to find the affected OS version, which I suspect is some faulty vendor's implementation of some codec in Android 12, but I couldn't reproduce it using an emulator.

**Comment by Destinyg133** [comment]
> I'm sorry to hear that, could you try again with [this one instead](https://github.com/element-hq/element-x-android/pull/4257#issuecomment-2648735567)?
> 
> Here we try to use a time interpolator that forces the timestamps to be linear, which should fix the issue, but I'm not sure if that could break the video somehow. I'm also trying to find the affected OS version, which I suspect is some faulty vendor's implementation of some codec in Android 12, but I couldn't reproduce it using an emulator.

Now its just neverending loop of sendings (it never stops)
No error this time
I will still include log cause it has a lot of audio error trying again etc

[logcat (3).log](https://github.com/user-attachments/files/18739784/logcat.3.log)

**Comment by Destinyg133** [comment]
@jmartinesp hi, any news or if you have suggestion if i can try anything to help you rule out issue?

**Comment by jmartinesp** [comment]
Sorry for the late reply. It seems like the issue is caused by either some faulty codec implementation in your vendor's version of Android, or by some bad interaction between the codec and the library we're using to transcode the video. Since we can't fix any of these issues what we'll do instead is try to detect this transcoding error and send the file as is as a fallback option.
