### ISSUE TITLE
Messages in timeline out of order

### ISSUE THREAD

**Issue by kieranlane** [element-hq/element-x-android#4425]
### Steps to reproduce

Sync issues when scrolling back to the previous day in messages. Messages end up out of order with messages from this morning (05:54 in the screenshot) followed by messages from 14 Feb.

Restarting the app temporarily corrects, but it has happened twice for me in the same room. I started seeing this in some other rooms today as well.

Our homeserver’s connectivity has been intermittent over the past couple of weeks, not sure if the disconnected states are contributing.

#### What did you expect?

Messages to be correctly sorted in chronological order.

#### What happened instead?

Some messages, whilst the date/time of the message are correct, appear out of order. Messages for today appear before messages for previous days (even though the app knows the messages dates)

### Your phone model

Samsung SM-S931U1

### Operating system version

Android 15

### Application version and app store

25.03.0

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by Destinyg133** [comment]
Can confirm this as I have stated it in different issue under point 3. It is rare but it can happend

https://github.com/element-hq/element-x-android/issues/4345#issuecomment-2729012843

**Comment by ledlamp** [comment]
I've been having this as well

**Comment by manuroe** [comment]
This issue is known on 25.03.0. It has been fixed in https://github.com/matrix-org/matrix-rust-sdk/pull/4748. Does it happen on 25.03.1 that is in open testing?

**Comment by Destinyg133** [comment]
https://github.com/user-attachments/assets/83626b5a-f8cf-47d5-acca-9d8c3403ed97

@manuroe still happens 25.03.04

**Comment by Destinyg133** [comment]
Still happens

![Image](https://github.com/user-attachments/assets/f4b4d09c-2361-45f3-84b1-6adf15233b75)
