### ISSUE TITLE
Crash on Element Call

### ISSUE THREAD

**Issue by aerusso** [element-hq/element-x-android#4774]
### Steps to reproduce

1. Go to a chat
2. Press the video button to start a call

#### What did you expect?
I expected a video call to start.

#### What happened instead?
The screen changes to an activity titled "Element Call" with a spinning wheel with "Please Wait" in the content area.  Then after a short while (less than a second), that activity closes, goes to a blank activity with another spinning wheel. That closes, and then another users chat opens.

If you try this a couple times, the app will just crash when you press the video call button.

#### More information
I was able to make one call, which no one joined and I then left.  I restarted the phone, but that doesn't seem to change anything.  This is very reproducible (I cannot make any calls).

### Your phone model

Pixel 6a

### Operating system version

LineageOS (microG) 22.2

### Application version and app store

Element X 25.05.0 (fdroid)

### Homeserver

Synapse 1.130.0

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by escix** [comment]
> I can make calls just fine on Schildichat (fdroid version 0.10.0-ex_24_4_2), so it's not a completely broken server. That version of Schildichat is from a little over a month ago, and presumably they use the common android element libraries (i.e., has something changed recently?).
> 
> Also, is this problem widespread and known, or am I the only one experiencing it?

See bug fix on here: https://github.com/element-hq/element-x-android/releases/tag/v25.05.1

But for me and some of the others, the element call notification after 25.04.3 is broken (including 25.05.4. 

So I reverted to 25.04.3 for now until the element call and notifications are fixed.

https://github.com/element-hq/element-x-android/issues/4714

https://github.com/element-hq/element-x-android/issues/4720

https://github.com/element-hq/element-x-android/issues/4737

https://github.com/element-hq/element-x-android/issues/4763

**Comment by escix** [comment]
> [@escix](https://github.com/escix) Thanks for pointing this out. Do you happen to know why the f-droid (and google) versions are so out of date? Also, did you downgrade your installed version, or did you uninstall/reinstall lower version (i.e., wipe all your data)? I'm wary of doing that, since every time I have in the past I get a bunch of grey "authenticity cannot be guaranteed" shield warnings.

The version mismatch is due to their own process timing,

Downgrade is only possible by remove current and install lower version.

I also have element-desktop running in the PC so I verify with that. It can also take some time to sync all messages.

It is risky, but as I have all my messages in the desktop, I am not overly concerned.

One of the biggest issue is Element-X still not supporting export/import room keys.
https://github.com/element-hq/element-x-android/issues/4610

**Comment by bmarty** [comment]
As @escix , the crash has been fixed in the latest version, now available on F-Droid. Also we have enforced our release process to ensure that such crash does not reach production anymore.

**Comment by aerusso** [comment]
@bmarty Due to #4788, this was not available in fdroid for arm64-v8a until very recently.  It still isn't available for x86 and x86_64 due to the same.
