### ISSUE TITLE
The app does not accept shares from certain apps.

### ISSUE THREAD

**Issue by YamatoRyou** [element-hq/element-x-android#5781]
### Steps to reproduce

1. Install MacroDroid and create a macro within it;
2. Save and share the macro after creation;
3. Select EXA as the first target for sending the macro, then select a room as the second target, and click "Send".

#### What did you expect?
n/a

#### What happened instead?
EXA error message: Failed to handle incoming share intent.
However, other apps can process it normally.
<img width="405" height="577" alt="Image" src="https://github.com/user-attachments/assets/0569f9b2-8906-444c-9cf1-8e1ce28fbdbe" />
### If you click the "Back" button (green arrow point to) at this point, EXA will crash.

----
Logs:
[{E4539EE7-BF93-AF7E-DBD7-5B560292D620}.zip](https://github.com/user-attachments/files/23655357/E4539EE7-BF93-AF7E-DBD7-5B560292D620.zip)
Password: `{24EB9E19-DE22-10C5-1AEF-69C05BD8E4E7}`
**Please download this file as soon as possible.**

### Your phone model

OnePlus MT2111

### Operating system version

Oxygen OS 15 (Android 15)

### Application version and app store

Element X Android 25.11.2

### Homeserver

Synapse 1.142.0

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
I believe this was just fixed by https://github.com/element-hq/element-x-android/pull/5773.

**Comment by YamatoRyou** [comment]
> I believe this was just fixed by [#5773](https://github.com/element-hq/element-x-android/pull/5773).

In the recent nightly build (ece47a42), the crash issue has indeed been fixed, but sharing from MacroDroid is still not accepted.

**Comment by jmartinesp** [comment]
@YamatoRyou please try the APK in https://github.com/element-hq/element-x-android/pull/5785 once it's uploaded. It fixed the issue for me, but I'd like to double check the fix.

**Comment by YamatoRyou** [comment]
> [@YamatoRyou](https://github.com/YamatoRyou) please try the APK in [#5785](https://github.com/element-hq/element-x-android/pull/5785) once it's uploaded. It fixed the issue for me, but I'd like to double check the fix.

Tested and fixed.
App: `01fc964c`
